# Dataset documentation --------------------------------------------------

#' Example MAF-like mutation data (internal)
#'
#' A small simulated MAF-like data frame with 40 samples and a handful of
#' genes, generated by `data-raw/make_example_data.R`. Samples were drawn
#' from four latent mutation programmes (clusters) so that the Jaccard
#' clustering functions can be demonstrated and tested.
#'
#' This is an internal dataset: it exists so that the function examples and
#' the test suite run in well under a second on a toy cohort, and it is kept
#' out of the README data description. Use `LCBM_panel_maf` or
#' `LCBM_WES_maf` for the real cohorts.
#'
#' @format A data frame with columns `Tumor_Sample_Barcode`, `Hugo_Symbol`,
#'   `Chromosome`, `Start_Position`, `End_Position`, `Reference_Allele`,
#'   `Tumor_Seq_Allele2`, `Variant_Classification` and `Variant_Type`.
#' @source Simulated data.
#' @keywords internal
"example_maf"

#' Example survival data (internal)
#'
#' Simulated overall-survival data for the 40 samples of `example_maf`.
#' Cluster 4 was generated with a worse prognosis.
#'
#' Like `example_maf` this is an internal dataset used by the function
#' examples and the test suite.
#'
#' @format A data frame with columns `ID`, `OS`, `status` (0/1) and
#'   `cluster` (1-4).
#' @source Simulated data.
#' @keywords internal
"example_survival"

#' LCBM panel cohort MAF object
#'
#' A `MAF` object (from the `maftools` package) holding the harmonised
#' somatic mutations of the LCBM panel cohort: the Huashan panel cohort
#' merged with the cBioPortal (MSK-IMPACT) cohort, restricted to the 298
#' genes shared by the Huashan panel and MSK-505, and filtered to
#' VAF >= 2% (rows with a missing VAF are kept).
#'
#' This is the direct input of the panel Jaccard 4-subtype clustering with
#' `max_features = 20`, `enhancement = 0.6`,
#' `clustering_method = "ward.D2"`, `n_clusters = 4` and
#' `drop_empty_samples = TRUE`, which yields 342 samples in four clusters
#' of 178 / 65 / 73 / 26 (see `inst/examples/LCBM_reproduction.R`).
#'
#' The `@data` slot carries the harmonised MAF data frame with
#' `Tumor_Sample_Barcode`, `Hugo_Symbol`, `Chromosome`, `Start_Position`,
#' `End_Position`, `Reference_Allele`, `Tumor_Seq_Allele2`,
#' `Variant_Classification`, `Variant_Type`, the depth / VAF columns
#' (`DP`, `ref_depth`, `alt_depth`, `VAF`, `n_ref_depth`, `n_alt_depth`) and
#' annotation columns (`protein_change`, `transcript_change`,
#' `variant_consequence`, `clinsig`, `transcript_id`, `exon`) plus
#' `cohort_name` (`"Huashan"` or `"cbioportal"`).
#'
#' Pseudo-identifiers such as the sample barcodes are published as-is; the
#' package authors are responsible for the ethical clearance of this data.
#'
#' @format A `MAF` object: 4691 variants, 358 samples, 292 genes.
#' @source Huashan panel cohort and cBioPortal MSK-IMPACT cohort, combined
#'   by the LCBM / HSYY analysis pipeline
#'   (`260916_maf_panel299_vaf002_panel.rds`).
"LCBM_panel_maf"

#' LCBM WES cohort MAF object
#'
#' A `MAF` object (from the `maftools` package) holding the harmonised
#' somatic mutations of the LCBM whole-exome cohort: the WES_SHANGHAI
#' cohort merged with the cellreport_WES cohort, put through the same
#' 298-gene restriction and VAF >= 2% filter as the panel cohort.
#'
#' This is the direct input of the WES Jaccard 4-subtype clustering with the
#' same parameters as the panel cohort
#' (`max_features = 20`, `enhancement = 0.6`,
#' `clustering_method = "ward.D2"`, `n_clusters = 4`,
#' `drop_empty_samples = TRUE`), which yields 145 samples in four clusters
#' of 28 / 71 / 28 / 18. Panel and WES samples are clustered separately on
#' purpose: their assayed gene sets differ too much for a joint clustering
#' to be interpreted biologically.
#'
#' The `@data` slot carries the same columns as `LCBM_panel_maf`, with
#' `cohort_name` being `"WES_SHANGHAI"` or `"cellreport_WES"`.
#'
#' @format A `MAF` object: 1585 variants, 157 samples, 266 genes.
#' @source WES_SHANGHAI cohort and cellreport_WES cohort, harmonised by the
#'   LCBM / HSYY analysis pipeline
#'   (`260916_maf_panel299_vaf002_WES.rds`).
"LCBM_WES_maf"

#' LCBM sample annotation table
#'
#' Clinical annotation for the 515 samples of the LCBM panel
#' (`LCBM_panel_maf`) and WES (`LCBM_WES_maf`) cohorts, plus five
#' cohort-level records, as exported by the LCBM / HSYY analysis pipeline.
#'
#' Columns cover overall, progression-free and CNS survival
#' (`OS_time` / `OS_status`, `PFS_time` / `PFS_status`,
#' `CNS_time` / `CNS_status`, `Intracranial_progression`), demographics
#' (`Sex`, `Age`, `KPS`, `Smoking`), tumour timing
#' (`Metachronous_vs_Synchronous`), treatment history
#' (`Prior_*` / `Post_*` and `Treatment_regimen`) and the `Histology`
#' label used by the subtype figures. `Histology` follows the cBioPortal
#' vocabulary (`LUAD`, `LUSC`, `SCLC`, `LCNEC`, `NET`, `LCC`, `NSCLC`,
#' `Other`) and is mapped to the four analysis subtypes
#' `AdC` / `SqCC` / `SCLC` / `LCNEC` downstream; 31 samples carry `NA`.
#'
#' The table is keyed on `Tumor_Sample_Barcode`; the accompanying
#' `cohort_name` distinguishes `"Huashan"`, `"cbioportal"`,
#' `"WES_SHANGHAI"` and `"cellreport_WES"`.
#'
#' Pseudo-identifiers such as the sample barcodes are published as-is; the
#' package authors are responsible for the ethical clearance of this data.
#'
#' @format A data frame with 520 rows and 29 columns.
#' @source LCBM / HSYY analysis pipeline
#'   (`260916_allsample_meta.csv`).
"LCBM_sample_annotation"
